name: Process pull requests
on:
  pull_request:
    types: [opened, edited]

jobs:
  semantic-pr-title:
    runs-on: ubuntu-24.04
    steps:
      - uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
