name: Process pull requests
on:
  pull_request:
    types: [opened, edited]

jobs:
  dependabot:
    runs-on: ubuntu-24.04
    if: ${{ github.actor == 'renovate[bot]' && github.event.action == 'opened' }}
    permissions:
      contents: "write"
      pull-requests: "write"
    steps:
      - name: Auto-merge PR
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  semantic-pr-title:
    runs-on: ubuntu-24.04
    steps:
      - uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
